// Official NEAR Example Templates
// These templates are seeded on backend startup and cannot be deleted

export interface OfficialTemplateConfig {
  id: string;
  name: string;
  description: string;
  github_url: string;
  github_branch: string;
  github_path: string | null;
  category: string;
  difficulty: 'Beginner' | 'Intermediate' | 'Advanced';
  icon: string;
  tags: string[];
}

export const OFFICIAL_TEMPLATES: OfficialTemplateConfig[] = [
  {
    id: '00000000-0000-0000-0000-000000000001',
    name: 'Counter',
    description: 'A simple counter contract demonstrating state management and basic NEAR SDK patterns. Perfect for learning the fundamentals.',
    github_url: 'https://github.com/near-examples/counters',
    github_branch: 'main',
    github_path: 'contract-rs',
    category: 'Basic',
    difficulty: 'Beginner',
    icon: 'Code2',
    tags: ['counter', 'beginner', 'state-management'],
  },
  {
    id: '00000000-0000-0000-0000-000000000002',
    name: 'Hello World',
    description: 'The classic Hello World contract that stores and retrieves a greeting message. Great starting point for NEAR development.',
    github_url: 'https://github.com/near-examples/hello-near-examples',
    github_branch: 'main',
    github_path: 'contract-rs',
    category: 'Basic',
    difficulty: 'Beginner',
    icon: 'MessageCircle',
    tags: ['hello-world', 'beginner', 'greeting'],
  },
  {
    id: '00000000-0000-0000-0000-000000000003',
    name: 'Fungible Token',
    description: 'NEP-141 compliant fungible token implementation. Create your own token with transfer, storage management, and metadata support.',
    github_url: 'https://github.com/near-examples/FT',
    github_branch: 'main',
    github_path: null,
    category: 'Token',
    difficulty: 'Intermediate',
    icon: 'Coins',
    tags: ['nep-141', 'fungible-token', 'token', 'defi'],
  },
  {
    id: '00000000-0000-0000-0000-000000000004',
    name: 'Non-Fungible Token',
    description: 'NEP-171 compliant NFT implementation with minting, transfers, approvals, and enumeration. Build your own NFT collection.',
    github_url: 'https://github.com/near-examples/NFT',
    github_branch: 'main',
    github_path: null,
    category: 'Token',
    difficulty: 'Intermediate',
    icon: 'Image',
    tags: ['nep-171', 'nft', 'collectibles', 'digital-assets'],
  },
  {
    id: '00000000-0000-0000-0000-000000000005',
    name: 'Cross Contract Calls',
    description: 'Learn how to make cross-contract calls between NEAR smart contracts. Essential pattern for building composable applications.',
    github_url: 'https://github.com/near-examples/cross-contract-calls',
    github_branch: 'main',
    github_path: 'contract-simple-rs',
    category: 'Advanced',
    difficulty: 'Advanced',
    icon: 'Link2',
    tags: ['cross-contract', 'promises', 'callbacks', 'composability'],
  },
  {
    id: '00000000-0000-0000-0000-000000000006',
    name: 'NEAR Drop',
    description: 'Smart contract for creating and claiming NEAR, FT, and NFT drops via the linkdrop protocol. Supports batch airdrops and time-locked drops.',
    github_url: 'https://github.com/near-examples/near-drop',
    github_branch: 'main',
    github_path: null,
    category: 'Utility',
    difficulty: 'Intermediate',
    icon: 'Gift',
    tags: ['drop', 'airdrop', 'linkdrop', 'near', 'nft', 'fungible-token'],
  },
  {
    id: '00000000-0000-0000-0000-000000000007',
    name: 'NEAR Indexer',
    description: 'NEAR Indexer Framework example that logs blocks, chunks, transactions, receipts, execution outcomes, and state changes from the NEAR blockchain.',
    github_url: 'https://github.com/near-examples/near-indexer',
    github_branch: 'main',
    github_path: null,
    category: 'Indexer',
    difficulty: 'Advanced',
    icon: 'Database',
    tags: ['indexer', 'near-indexer-framework', 'blockchain-data', 'advanced'],
  },
  {
    id: '00000000-0000-0000-0000-000000000008',
    name: 'Lake Framework Indexer',
    description: 'Rust indexer using NEAR Lake Framework to stream and process blockchain data, watching for transactions targeting specific accounts or contracts.',
    github_url: 'https://github.com/near-examples/indexer-near-lake-framework',
    github_branch: 'main',
    github_path: 'rust',
    category: 'Indexer',
    difficulty: 'Advanced',
    icon: 'Layers',
    tags: ['lake-framework', 'indexer', 'blockchain-data', 'streaming', 'advanced'],
  },
  {
    id: '00000000-0000-0000-0000-000000000009',
    name: 'Storage & Collections',
    description: 'Learn NEAR\'s on-chain storage collections: Vector, LookupMap, UnorderedMap, LookupSet, and UnorderedSet with practical usage examples.',
    github_url: 'https://github.com/near-examples/storage-examples',
    github_branch: 'main',
    github_path: 'collections-rs',
    category: 'Basic',
    difficulty: 'Beginner',
    icon: 'Archive',
    tags: ['storage', 'collections', 'data-structures', 'beginner'],
  },
  {
    id: '00000000-0000-0000-0000-000000000010',
    name: 'Factory Contract',
    description: 'Deploy and manage child contracts from a parent factory contract. Learn how to create sub-accounts and deploy WASM bytecode programmatically.',
    github_url: 'https://github.com/near-examples/factory-rust',
    github_branch: 'main',
    github_path: null,
    category: 'Advanced',
    difficulty: 'Advanced',
    icon: 'Factory',
    tags: ['factory', 'sub-accounts', 'deployment', 'advanced'],
  },
  {
    id: '00000000-0000-0000-0000-000000000011',
    name: 'Contract Upgrades',
    description: 'Learn how to perform state migrations and contract upgrades in NEAR: basic updates, enum-versioned state, self-updates, and multi-version migrations.',
    github_url: 'https://github.com/near-examples/update-migrate-rust',
    github_branch: 'main',
    github_path: null,
    category: 'Advanced',
    difficulty: 'Advanced',
    icon: 'RefreshCw',
    tags: ['upgrades', 'migration', 'state', 'advanced', 'production'],
  },
  {
    id: '00000000-0000-0000-0000-000000000012',
    name: 'Auction',
    description: 'A time-boxed auction contract where users bid with NEAR tokens. Tracks the highest bidder and auto-refunds previous bids. Great intro to timed logic and deposits.',
    github_url: 'https://github.com/near-examples/auctions-tutorial',
    github_branch: 'main',
    github_path: 'contract-rs/01-basic-auction',
    category: 'DeFi',
    difficulty: 'Intermediate',
    icon: 'Gavel',
    tags: ['auction', 'bidding', 'defi', 'deposits', 'time-based'],
  },
  {
    id: '00000000-0000-0000-0000-000000000013',
    name: 'Donation',
    description: 'A donation contract that forwards NEAR to a designated beneficiary. Tracks all donor contributions in an on-chain ledger with full query support.',
    github_url: 'https://github.com/near-examples/donation-examples',
    github_branch: 'main',
    github_path: 'contract-rs',
    category: 'Basic',
    difficulty: 'Beginner',
    icon: 'Heart',
    tags: ['donation', 'charity', 'payments', 'beginner'],
  },
  {
    id: '00000000-0000-0000-0000-000000000014',
    name: 'Guest Book',
    description: 'A persistent on-chain guest book where users post messages. Premium messages require a minimum NEAR deposit. Demonstrates storage patterns and pagination.',
    github_url: 'https://github.com/near-examples/guest-book-examples',
    github_branch: 'main',
    github_path: 'contract-rs',
    category: 'Basic',
    difficulty: 'Beginner',
    icon: 'BookMarked',
    tags: ['guest-book', 'messages', 'storage', 'beginner', 'social'],
  },
  {
    id: '00000000-0000-0000-0000-000000000015',
    name: 'Coin Flip',
    description: 'A provably fair coin-flip game using NEAR\'s on-chain randomness. Players guess heads or tails and earn points for correct guesses.',
    github_url: 'https://github.com/near-examples/coin-flip-examples',
    github_branch: 'main',
    github_path: 'contract-rs',
    category: 'Game',
    difficulty: 'Beginner',
    icon: 'Dices',
    tags: ['game', 'randomness', 'coin-flip', 'beginner', 'fun'],
  },
];
